---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lyvibvjb/app.neunoi.it
    - /bin/cp -R server/* $DEPLOYPATH
    - /bin/cp server/.env $DEPLOYPATH
    - /bin/cp server/package.json $DEPLOYPATH
